FROM rockylinux/rockylinux:8.9
ENV container docker
# apache
RUN dnf -y install httpd

# java
RUN yum install -y java-21-openjdk

# java related pack

#python related pack
RUN dnf install curl gcc openssl-devel bzip2-devel libffi-devel zlib-devel wget make -y

#python main
RUN dnf -y install python3.11

# postgresql 15
RUN yum install -y @postgresql:15

CMD ["/usr/sbin/init"]
